# Generated by Django 5.0 on 2024-09-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstoreapp', '0002_addbooks_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbooks',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
