# Generated by Django 5.0 on 2024-09-27 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstoreapp', '0006_profile_delete_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookstoreapp.profile'),
        ),
    ]
