# Generated by Django 5.1.1 on 2024-11-29 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstoreapp', '0009_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='cover_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='openlibrary_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
